project:
  type: website

website:
  title: Aaron Gaines
  navbar:
    collapse: true
    right:
      - href: index.qmd
        text: Home
      - href: portfolio.qmd
        text: Portfolio
      - href: about.qmd
        text: About Me
      - text: Contact
        menu:
          - href: https://www.linkedin.com/in/aaron-m-gaines/
            text: LinkedIn


format:
  html:
    theme: pulse
    css: styles.css
    toc: true
    max-width: 2800px

execute: 
  freeze: auto

