---
title: "About Me"
---

My name is Aaron Gaines, and I am 29 years old. I have been working as a research assistant at California State University, Northridge (CSUN) since October 2019, where I also received a Bachelors in Geography - Geographic Information Science in June 2021. I have also recently received a graduate certificate in Data Science from the UCLA Extension program.

### **Experience**

Most of my time as a research assistant has been spent working on updating the National Hydrography Dataset (NHD), a USGS database, for the California Department of Water Resources. This involved creating, editing, and managing digitized hydrographic features while maintaining a minimum level of quality required by the USGS to ensure data interoperability between different state agency’s update efforts. Overtime my responsibilities within the team grew from simple first pass editing to managing a job from start to finish, including performing quality control checks on other editor's work to ensure our updates can be merged into the main database.

More recently I have been working on a pilot project investigating the possible effects of sea level rise on groundwater levels and contamination, as well as disadvantaged communities (DACs). This has involved doing literature reviews on similar projects, aggregating, and presenting that information to a larger team. With feedback I then would apply the methodologies found in different papers to our data to compare and discover the different advantages and drawbacks. An example of this was to look at how different state agencies would designate DACs. From this the group decided on a methodology that seemed to be the most complete, which happened to be the CalEnviroScreen (CES). I then used their white paper to emulate some of their methodologies in determining environmental and social disadvantages with python and ArcGIS Pro.  For example, spatial analysis of monitoring wells and their sample data to determine a blockgroup's exposure to specific groundwater contamination. When we found their determination of data quality not to our liking, I used the American Housing Survey variance replicate data to determine the uncertainty in our social vulnerability index, a method described by (et al.). This project has grown my skills in literature review, effectively presenting technical papers and methodologies and emulation of said methodologies with Python.

### **Skills**

I am very proficient in the use of the ESRI stack of products, particularly ArcGIS Pro and ArcGIS Online as well as automating tasks using the ArcGIS model builder and ArcPy. While I do not have a lot of experience with QGIS, that is something I would like to change as I have a fondness for opensource technology for the simple fact that it allows others to replicate and expand on the work of others more easily. I also have a decent amount of experience in Python and many of its data science libraries including Pandas, Matplotlib, Scikit-Learn and the Tensorflow Keras API. I have no problem writing custom classes or modules/packages where necessary. I also have some experience with PostgreSQL and PostGIS queries.

### **Why GIS and Data Science?**

I enjoy looking at problems from a big picture perspective, and I really enjoy how GIS and data science let me explore and solve problems concerning such a wide range of industries and topics. And while I am constantly learning new things directly related to my work, like tricking machine learning models, I also enjoy learning about a vast range of other topics related to science. Whether its material science or astrophysics, I am always intrigued by the process solving puzzles and discovering new things.
